INSERT INTO addresses (street, postal_code, city, country) VALUES ('Ekogatan 12', '12345', 'Stockholm', 'Sverige'), ('Lundagatan 8', '54321', 'Göteborg', 'Sverige'), ('Skogsvägen 4', '67890', 'Malmö', 'Sverige'), ('Kyrkogatan 2', '98765', 'Uppsala', 'Sverige'), ('Sjövägen 6', '13579', 'Linköping', 'Sverige');

INSERT INTO users (first_name, last_name, email, phone, address_id, member_type) VALUES ('Emma', 'Johnson', 'emma.johnson@email.com', '555-123-4567', 1, 'standard'), ('Liam', 'Smith', 'liam.smith@email.com', '555-234-5678', 2, 'standard'), ('Olivia', 'Brown', 'olivia.brown@email.com', '555-345-6789', 3, 'standard'), ('Noah', 'Davis', 'noah.davis@email.com', '555-456-7890', 4, 'standard'), ('Ava', 'Wilson', 'ava.wilson@email.com', '555-567-8901', 5, 'standard');

INSERT INTO posts (title, content) VALUES ('Enkla tips för bättre hälsa', 'Vill du förbättra din hälsa? Här är några enkla tips:\n\n1. Drick mer vatten: Ha alltid en vattenflaska nära.\n2. Rör på dig: Gå minst 30 minuter om dagen.\n3. Ät grönsaker: Lägg till en grönsak vid varje måltid.\n4. Sov bättre: Sikta på 7-8 timmars sömn.\n5. Stressa ner: Prova meditation eller yoga.');
INSERT INTO posts (title, content) VALUES ('Utforska Sveriges nationalparker', 'Sverige har många vackra nationalparker. Här är några favoriter:\n\n1. Abisko: Perfekt för att se norrsken.\n2. Sarek: Fantastiskt för vandring och äventyr.\n3. Tyresta: Nära Stockholm, perfekt för en dagsutflykt.');
INSERT INTO posts (title, content) VALUES ('Fem snabba middagsrecept', 'Behöver du snabba middagar? Prova dessa:\n\n1. Pasta med tomatsås: Enkel och god.\n2. Kycklingwok: Snabb och hälsosam.\n3. Soppa: Gör en stor sats och frys in.\n4. Tacos: Anpassa efter smak.\n5. Sallad: Lägg till protein för en mättande måltid.');
INSERT INTO posts (title, content) VALUES ('Fördelar med att läsa böcker','Att läsa böcker har många fördelar:\n\n1. Minskar stress: Att läsa kan lugna sinnet.\n2. Ökar kunskap: Du lär dig nya saker.\n3. Förbättrar koncentration: Tränar hjärnan.\n4. Underhållning: En bra bok kan vara lika spännande som en film.');
INSERT INTO posts (title, content) VALUES ('Tips för att jobba hemifrån','Jobbar du hemifrån? Här är några tips:\n\n1. Sätt rutiner: Ha fasta arbetstider.\n2. Ta pauser: Glöm inte att ta raster.\n3. Skapa en arbetsplats: Ha en specifik plats för arbete.\n4. Håll kontakten: Prata med kollegor regelbundet.\n5. Håll dig aktiv: Ta korta promenader under dagen.');
